title: Subcommission on Permian Stratigraphy
email: nicholas.car@surroundaustralia.com
description: >- # this means to ignore newlines until "baseurl:"
  The small website for the Permian subcommission of the International Commission on Stratigraphy, online at <http://Permian.stratigraphy.org>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
